-- Inserção na tabela MEMBROS
INSERT INTO USR_FITNESS_MEMBROS (MEMBRO_ID, NOME, DATA_NASCIMENTO, TELEFONE, EMAIL)
VALUES (USR_FITNESS_SEQ_MEMBROS.NEXTVAL, 'Vitor Azevedo', TO_DATE('2003-10-13', 'YYYY-MM-DD'), '11999999999', 'vitor@example.com');

INSERT INTO USR_FITNESS_MEMBROS (MEMBRO_ID, NOME, DATA_NASCIMENTO, TELEFONE, EMAIL)
VALUES (USR_FITNESS_SEQ_MEMBROS.NEXTVAL, 'Kaique Oliveira', TO_DATE('2004-10-13', 'YYYY-MM-DD'), '11777777777', 'kaique@example.com');

INSERT INTO USR_FITNESS_MEMBROS (MEMBRO_ID, NOME, DATA_NASCIMENTO, TELEFONE, EMAIL)
VALUES (USR_FITNESS_SEQ_MEMBROS.NEXTVAL, 'Mia Delgado', TO_DATE('2002-10-25', 'YYYY-MM-DD'), '11666666666', 'mia@example.com');

INSERT INTO USR_FITNESS_MEMBROS (MEMBRO_ID, NOME, DATA_NASCIMENTO, TELEFONE, EMAIL)
VALUES (USR_FITNESS_SEQ_MEMBROS.NEXTVAL, 'Gustavo Yukihiro', TO_DATE('2002-01-18', 'YYYY-MM-DD'), '11555555555', 'gustavo@example.com');

INSERT INTO USR_FITNESS_MEMBROS (MEMBRO_ID, NOME, DATA_NASCIMENTO, TELEFONE, EMAIL)
VALUES (USR_FITNESS_SEQ_MEMBROS.NEXTVAL, 'Lana Menegel', TO_DATE('2002-10-25', 'YYYY-MM-DD'), '11666666666', 'lana@example.com');


-- Inserção na tabela PLANOS_TREINAMENTO
INSERT INTO USR_FITNESS_PLANOS_TREINAMENTO (PLANO_ID, NOME, DESCRICAO, DURACAO_SEMANAS)
VALUES (USR_FITNESS_SEQ_PLANOS_TREINAMENTO.NEXTVAL, 'Plano Básico', 'Plano para iniciantes com foco em resistência', 8);

INSERT INTO USR_FITNESS_PLANOS_TREINAMENTO (PLANO_ID, NOME, DESCRICAO, DURACAO_SEMANAS)
VALUES (USR_FITNESS_SEQ_PLANOS_TREINAMENTO.NEXTVAL, 'Plano Básico', 'Plano para iniciantes com foco em resistência muscular e adaptação ao treino.', 8);

INSERT INTO USR_FITNESS_PLANOS_TREINAMENTO (PLANO_ID, NOME, DESCRICAO, DURACAO_SEMANAS)
VALUES (USR_FITNESS_SEQ_PLANOS_TREINAMENTO.NEXTVAL, 'Plano Intermediário', 'Plano para praticantes com alguma experiência, com foco em hipertrofia e aumento de força.', 12);

INSERT INTO USR_FITNESS_PLANOS_TREINAMENTO (PLANO_ID, NOME, DESCRICAO, DURACAO_SEMANAS)
VALUES (USR_FITNESS_SEQ_PLANOS_TREINAMENTO.NEXTVAL, 'Plano Avançado', 'Plano para atletas avançados com ênfase em força máxima e periodização.', 16);

INSERT INTO USR_FITNESS_PLANOS_TREINAMENTO (PLANO_ID, NOME, DESCRICAO, DURACAO_SEMANAS)
VALUES (USR_FITNESS_SEQ_PLANOS_TREINAMENTO.NEXTVAL, 'Plano de Condicionamento', 'Plano voltado para melhora do condicionamento físico e desempenho aeróbico.', 10);

INSERT INTO USR_FITNESS_PLANOS_TREINAMENTO (PLANO_ID, NOME, DESCRICAO, DURACAO_SEMANAS)
VALUES (USR_FITNESS_SEQ_PLANOS_TREINAMENTO.NEXTVAL, 'Plano Funcional', 'Plano que combina exercícios dinâmicos para força, equilíbrio e mobilidade.', 8);

INSERT INTO USR_FITNESS_PLANOS_TREINAMENTO (PLANO_ID, NOME, DESCRICAO, DURACAO_SEMANAS)
VALUES (USR_FITNESS_SEQ_PLANOS_TREINAMENTO.NEXTVAL, 'Plano Pós-Reabilitação', 'Plano criado para auxiliar na recuperação de lesões com exercícios específicos.', 6);

INSERT INTO USR_FITNESS_PLANOS_TREINAMENTO (PLANO_ID, NOME, DESCRICAO, DURACAO_SEMANAS)
VALUES (USR_FITNESS_SEQ_PLANOS_TREINAMENTO.NEXTVAL, 'Plano Perda de Peso', 'Plano com foco em redução de peso corporal e aumento do gasto calórico.', 12);

INSERT INTO USR_FITNESS_PLANOS_TREINAMENTO (PLANO_ID, NOME, DESCRICAO, DURACAO_SEMANAS)
VALUES (USR_FITNESS_SEQ_PLANOS_TREINAMENTO.NEXTVAL, 'Plano Personalizado', 'Plano adaptado às necessidades específicas de cada aluno.', NULL);


-- Inserção na tabela EXERCICIOS
INSERT INTO USR_FITNESS_EXERCICIOS (EXERCICIO_ID, NOME, TIPO, DESCRICAO)
VALUES (USR_FITNESS_SEQ_EXERCICIOS.NEXTVAL, 'Supino Reto', 'Força', 'Exercício para peitorais e tríceps com barra ou halteres.');

INSERT INTO USR_FITNESS_EXERCICIOS (EXERCICIO_ID, NOME, TIPO, DESCRICAO)
VALUES (USR_FITNESS_SEQ_EXERCICIOS.NEXTVAL, 'Agachamento', 'Força', 'Exercício para fortalecer os músculos das pernas, com foco em quadríceps e glúteos.');

INSERT INTO USR_FITNESS_EXERCICIOS (EXERCICIO_ID, NOME, TIPO, DESCRICAO)
VALUES (USR_FITNESS_SEQ_EXERCICIOS.NEXTVAL, 'Supino reto', 'Força', 'Exercício para peito, focando no desenvolvimento do músculo peitoral.');

INSERT INTO USR_FITNESS_EXERCICIOS (EXERCICIO_ID, NOME, TIPO, DESCRICAO)
VALUES (USR_FITNESS_SEQ_EXERCICIOS.NEXTVAL, 'Corrida', 'Aeróbico', 'Exercício cardiovascular que melhora a resistência e a saúde cardiovascular.');
       
INSERT INTO USR_FITNESS_EXERCICIOS (EXERCICIO_ID, NOME, TIPO, DESCRICAO)
VALUES (USR_FITNESS_SEQ_EXERCICIOS.NEXTVAL, 'Remada curvada', 'Força', 'Exercício para trabalhar as costas e os músculos dorsais.');

INSERT INTO USR_FITNESS_EXERCICIOS (EXERCICIO_ID, NOME, TIPO, DESCRICAO)
VALUES (USR_FITNESS_SEQ_EXERCICIOS.NEXTVAL, 'Abdominal', 'Core', 'Exercício para fortalecer os músculos abdominais e melhorar a postura.');

INSERT INTO USR_FITNESS_EXERCICIOS (EXERCICIO_ID, NOME, TIPO, DESCRICAO)
VALUES (USR_FITNESS_SEQ_EXERCICIOS.NEXTVAL, 'Pular corda', 'Aeróbico', 'Exercício cardiovascular que melhora a coordenação e a resistência.');

INSERT INTO USR_FITNESS_EXERCICIOS (EXERCICIO_ID, NOME, TIPO, DESCRICAO)
VALUES (USR_FITNESS_SEQ_EXERCICIOS.NEXTVAL, 'Cadeira extensora', 'Força', 'Exercício isolado para os quadríceps, focando na extensão da perna.');

INSERT INTO USR_FITNESS_EXERCICIOS (EXERCICIO_ID, NOME, TIPO, DESCRICAO)
VALUES (USR_FITNESS_SEQ_EXERCICIOS.NEXTVAL, 'Puxada frente', 'Força', 'Exercício para costas, com ênfase na musculatura do latíssimo do dorso.');

INSERT INTO USR_FITNESS_EXERCICIOS (EXERCICIO_ID, NOME, TIPO, DESCRICAO)
VALUES (USR_FITNESS_SEQ_EXERCICIOS.NEXTVAL, 'Leg press', 'Força', 'Exercício para pernas, trabalhando quadríceps, glúteos e panturrilhas.');

INSERT INTO USR_FITNESS_EXERCICIOS (EXERCICIO_ID, NOME, TIPO, DESCRICAO)
VALUES (USR_FITNESS_SEQ_EXERCICIOS.NEXTVAL, 'Burpee', 'Condicionamento', 'Exercício funcional de alta intensidade, que envolve agachamento, salto e flexão de braço.');


-- Inserção na tabela HISTORICO_TREINAMENTO
INSERT INTO USR_FITNESS_HISTORICO_TREINAMENTO (HISTORICO_ID, MEMBRO_ID, PLANO_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (USR_FITNESS_SEQ_HISTORICO_TREINAMENTO.NEXTVAL, 1, 1, TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'), 'Concluído');

INSERT INTO USR_FITNESS_HISTORICO_TREINAMENTO (HISTORICO_ID, MEMBRO_ID, PLANO_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (USR_FITNESS_SEQ_HISTORICO_TREINAMENTO.NEXTVAL, 2, 2, TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2024-07-31', 'YYYY-MM-DD'), 'Concluído');

INSERT INTO USR_FITNESS_HISTORICO_TREINAMENTO (HISTORICO_ID, MEMBRO_ID, PLANO_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (USR_FITNESS_SEQ_HISTORICO_TREINAMENTO.NEXTVAL, 3, 3, TO_DATE('2024-03-15', 'YYYY-MM-DD'), NULL, 'Ativo');

INSERT INTO USR_FITNESS_HISTORICO_TREINAMENTO (HISTORICO_ID, MEMBRO_ID, PLANO_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (USR_FITNESS_SEQ_HISTORICO_TREINAMENTO.NEXTVAL, 4, 1, TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2024-09-30', 'YYYY-MM-DD'), 'Concluído');

INSERT INTO USR_FITNESS_HISTORICO_TREINAMENTO (HISTORICO_ID, MEMBRO_ID, PLANO_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (USR_FITNESS_SEQ_HISTORICO_TREINAMENTO.NEXTVAL, 5, 2, TO_DATE('2024-05-01', 'YYYY-MM-DD'), NULL, 'Ativo');


-- Inserção na tabela ROTINAS_TREINAMENTO
INSERT INTO USR_FITNESS_ROTINAS_TREINAMENTO (ROTINA_ID, PLANO_ID, EXERCICIO_ID, SERIES, REPETICOES, DESCANSO_SEGUNDOS)
VALUES (USR_FITNESS_SEQ_ROTINAS_TREINAMENTO.NEXTVAL, 1, 1, 4, 12, 60);

INSERT INTO USR_FITNESS_ROTINAS_TREINAMENTO (ROTINA_ID, PLANO_ID, EXERCICIO_ID, SERIES, REPETICOES, DESCANSO_SEGUNDOS)
VALUES (USR_FITNESS_SEQ_ROTINAS_TREINAMENTO.NEXTVAL, 1, 2, 4, 10, 90);

INSERT INTO USR_FITNESS_ROTINAS_TREINAMENTO (ROTINA_ID, PLANO_ID, EXERCICIO_ID, SERIES, REPETICOES, DESCANSO_SEGUNDOS)
VALUES (USR_FITNESS_SEQ_ROTINAS_TREINAMENTO.NEXTVAL, 2, 3, 5, 20, 60);

INSERT INTO USR_FITNESS_ROTINAS_TREINAMENTO (ROTINA_ID, PLANO_ID, EXERCICIO_ID, SERIES, REPETICOES, DESCANSO_SEGUNDOS)
VALUES (USR_FITNESS_SEQ_ROTINAS_TREINAMENTO.NEXTVAL, 2, 4, 4, 12, 75);

INSERT INTO USR_FITNESS_ROTINAS_TREINAMENTO (ROTINA_ID, PLANO_ID, EXERCICIO_ID, SERIES, REPETICOES, DESCANSO_SEGUNDOS)
VALUES (USR_FITNESS_SEQ_ROTINAS_TREINAMENTO.NEXTVAL, 3, 5, 3, 15, 90);

INSERT INTO USR_FITNESS_ROTINAS_TREINAMENTO (ROTINA_ID, PLANO_ID, EXERCICIO_ID, SERIES, REPETICOES, DESCANSO_SEGUNDOS)
VALUES (USR_FITNESS_SEQ_ROTINAS_TREINAMENTO.NEXTVAL, 3, 6, 4, 10, 60);

INSERT INTO USR_FITNESS_ROTINAS_TREINAMENTO (ROTINA_ID, PLANO_ID, EXERCICIO_ID, SERIES, REPETICOES, DESCANSO_SEGUNDOS)
VALUES (USR_FITNESS_SEQ_ROTINAS_TREINAMENTO.NEXTVAL, 4, 7, 4, 12, 90);

INSERT INTO USR_FITNESS_ROTINAS_TREINAMENTO (ROTINA_ID, PLANO_ID, EXERCICIO_ID, SERIES, REPETICOES, DESCANSO_SEGUNDOS)
VALUES (USR_FITNESS_SEQ_ROTINAS_TREINAMENTO.NEXTVAL, 4, 8, 3, 10, 60);

INSERT INTO USR_FITNESS_ROTINAS_TREINAMENTO (ROTINA_ID, PLANO_ID, EXERCICIO_ID, SERIES, REPETICOES, DESCANSO_SEGUNDOS)
VALUES (USR_FITNESS_SEQ_ROTINAS_TREINAMENTO.NEXTVAL, 5, 9, 5, 15, 80);

INSERT INTO USR_FITNESS_ROTINAS_TREINAMENTO (ROTINA_ID, PLANO_ID, EXERCICIO_ID, SERIES, REPETICOES, DESCANSO_SEGUNDOS)
VALUES (USR_FITNESS_SEQ_ROTINAS_TREINAMENTO.NEXTVAL, 5, 10, 4, 12, 60);