-- Sequência para MEMBROS
CREATE SEQUENCE USR_FITNESS_SEQ_MEMBROS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequência para PLANOS_TREINAMENTO
CREATE SEQUENCE USR_FITNESS_SEQ_PLANOS_TREINAMENTO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequência para EXERCICIOS
CREATE SEQUENCE USR_FITNESS_SEQ_EXERCICIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequência para HISTORICO_TREINAMENTO
CREATE SEQUENCE USR_FITNESS_SEQ_HISTORICO_TREINAMENTO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequência para ROTINAS_TREINAMENTO
CREATE SEQUENCE USR_FITNESS_SEQ_ROTINAS_TREINAMENTO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;





-- Criação das tabelas
CREATE TABLE USR_FITNESS_MEMBROS (
    MEMBRO_ID NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR2(15),
    EMAIL VARCHAR2(100)
);

-- Criação da tabela PLANOS_TREINAMENTO
CREATE TABLE USR_FITNESS_PLANOS_TREINAMENTO (
    PLANO_ID NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO CLOB,
    DURACAO_SEMANAS NUMBER
);

-- Criação da tabela EXERCICIO 
CREATE TABLE USR_FITNESS_EXERCICIOS (
    EXERCICIO_ID NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(50),
    DESCRICAO CLOB
);

-- Criação da tabela HISTORICO_TREINAMENTO
CREATE TABLE USR_FITNESS_HISTORICO_TREINAMENTO (
    HISTORICO_ID NUMBER NOT NULL PRIMARY KEY,
    MEMBRO_ID NUMBER NOT NULL,
    PLANO_ID NUMBER NOT NULL,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    STATUS VARCHAR2(50),
    CONSTRAINT FK_HISTORICO_MEMBRO FOREIGN KEY (MEMBRO_ID) REFERENCES USR_FITNESS_MEMBROS(MEMBRO_ID),
    CONSTRAINT FK_HISTORICO_PLANO FOREIGN KEY (PLANO_ID) REFERENCES USR_FITNESS_PLANOS_TREINAMENTO(PLANO_ID)
);

-- Criação da tabela ROTINA_TREINAMENTO
CREATE TABLE USR_FITNESS_ROTINAS_TREINAMENTO (
    ROTINA_ID NUMBER NOT NULL PRIMARY KEY,
    PLANO_ID NUMBER NOT NULL,
    EXERCICIO_ID NUMBER NOT NULL,
    SERIES NUMBER,
    REPETICOES NUMBER,
    DESCANSO_SEGUNDOS NUMBER,
    CONSTRAINT FK_ROTINAS_PLANO FOREIGN KEY (PLANO_ID) REFERENCES USR_FITNESS_PLANOS_TREINAMENTO(PLANO_ID),
    CONSTRAINT FK_ROTINAS_EXERCICIO FOREIGN KEY (EXERCICIO_ID) REFERENCES USR_FITNESS_EXERCICIOS(EXERCICIO_ID)
);